### ISSUE TITLE
How to fail action?

### ISSUE THREAD

**Issue by biegl** [garygrossgarten/github-action-ssh#1]
Hi, thanks for providing this action. Is there a way to fail the action based on the exit code of the commands that get executed on the remote host? 

Im am running `git push` remotely and it fails because it cannot push as there the origin has diverged. After the command has finished the action still returns successfully and the workflow continues. I am using the `@release` version

Any idea?

**Comment by biegl** [comment]
@garygrossgarten, any info on this one?

**Comment by biegl** [comment]
Created a PR #2  to fail the whole action when the executed command fails.

**Comment by garygrossgarten** [comment]
hey @biegl , I just published your changes to @test/0.4.3. Could you test if this fixes your issues and report back here?

I tested it with a simple node script that always fails when running and it seems to be working.

**Comment by biegl** [comment]
@garygrossgarten, tested it by returning `exit 1` in the SSH command. Works like a charm! 
Thanks for merging the changes.

**Comment by garygrossgarten** [comment]
Released it as a new version. Thanks!
