### ISSUE TITLE
ip or ifconfig not found

### ISSUE THREAD

**Issue by abakumov-v** [garygrossgarten/github-action-ssh#13]
Hi!

I have some GitHub Actions workflow file - this is a part of it:

```yml
      - name: Deploy via SSH - run app
        uses: garygrossgarten/github-action-ssh@release
        with:
          command: |
            HOST=$(hostname --ip-address)
            HOST2=$(ip -4 addr show docker0 | grep -Po 'inet \K[\d.]+')
            HOST3=$(ifconfig docker0 | grep 'inet' | cut -d: -f2 | awk '{print $2}')
            echo HOST=$HOST
            echo HOST2=$HOST2
            echo HOST3=$HOST3

            cd ${{ env.DEPLOY_DIR }}
            sed -i -E 's/SERVICE_AUTH_IMAGE=.*/SERVICE_AUTH_IMAGE='${{ env.VERSION }}'/g' .env
            sed -i -E 's/HOST_IP/'"$HOST"'/g' docker-compose.yml
            echo ${{ secrets.PACKAGES_READ_TOKEN }} | docker login ${{ env.DOCKER_REGISTRY_HOST }} -u ${{ secrets.DOCKER_LOGIN_USERNAME }} --password-stdin
            docker-compose pull
            docker-compose down
            docker-compose up -d
          host: ${{ secrets.DEPLOY_HOST }}
          port: ${{ secrets.DEPLOY_PORT }}
          username: ${{ secrets.DEPLOY_USER }}
          privateKey: ${{ secrets.DEPLOY_PRIVATE_KEY}}
```

Purpose of this code is deploy docker container to remote host with help of docker-compose.yml. But I need an IP address of `docker0` network from linux-host. On host I can use this commands as fine:

* `hostname --ip-address`
* `ip -4 addr show docker0 | grep -Po 'inet \K[\d.]+'`
* `ifconfig docker0 | grep 'inet' | cut -d: -f2 | awk '{print $2}'`

But when I'm trying use this commands in workflow file I'm get an error for 2nd and 3rd commands:
```
ip command not found
ifconfig command not found
```
![image](https://user-images.githubusercontent.com/6594815/93709869-a0136a00-fb4a-11ea-98b0-34011beeb655.png)

Tell me, please, how can I use the `ip` or `ifconfig` commands with this GitHub Action?

P.S. Thank you for this action - it works cool for me )

**Comment by garygrossgarten** [comment]
@abakumov-v Did you resolve your problem? I can't reproduce it on my side. Tried to use the ip command with this action and it works for me. Please reopen the issue and/or create a PR if you know how to resolve it.

**Comment by harrisoff** [comment]
similar issue:

```yaml
    steps:
    - name: run cmd
      uses: garygrossgarten/github-action-ssh@release
      with:
        command: |
          node --version
          npm --version
        username: root
        host: ${{ secrets.HOST }}
        privateKey: ${{ secrets.ID_RSA}}
```

![image](https://user-images.githubusercontent.com/29137942/113266186-8d52cc80-9307-11eb-823f-805d17af9ff9.png)

And the node version is actually v12.x

**Comment by lnfel** [comment]
> This is my guess: I use nvm to manage my node versions. `node` is set in `/usr/bin/` and nvm directory so the action could run the first one, yet `npm` is only set in nvm so it could not be found
> 
> However I did not install node v8.x

This is right, I am also using nvm and running `which npm` or `which node` brings `/home/username/.nvm/versions/node/v18.14.2/bin/npm` and `/home/username/.nvm/versions/node/v18.14.2/bin/node` respectively. I tried adding the `/home/username/.nvm/versions/node/v18.14.2/bin` path to github secrets.

Then use it as:
```yml
command: |
  ${{ secrets.NODE_BIN_PATH }}/npm run some:command
```
It tried to run the npm script but failed with:
```s
Error: Command exited with code 127
```
Because `/usr/bin/env: ‘node’ : No such file or directory`

Googling `/usr/bin/env: node: No such file or directory` showed a related issue:
https://stackoverflow.com/questions/26320901/cannot-install-nodejs-usr-bin-env-node-no-such-file-or-directory

One solution there suggested symlinking node and npm, which I think is the best solution if your server will only work with one version of node.
```s
sudo ln -s "$(which node)" /usr/bin/node
sudo ln -s "$(which npm)" /usr/bin/npm
```
We can now change the command to:
```yml
command: |
  npm run some:command
```
