### ISSUE TITLE
Question: Run npm install in directory

### ISSUE THREAD

**Issue by Nollknolle** [garygrossgarten/github-action-ssh#30]
Hello,
is it possible to run npm install in for example /opt/xyz?

I am very happy to receive any answers.
Thanks :D

**Comment by garygrossgarten** [comment]
Hey there,
I'd say it's definitely possible. 
Just make sure you have node installed on the server you're trying to run the command on.

**Comment by Nollknolle** [comment]
Ok thanks 🙏
