### ISSUE TITLE
Error: Timed out while waiting for handshake

### ISSUE THREAD

**Issue by devcarlos** [garygrossgarten/github-action-ssh#4]
I get this log from the GitHub Action:

> Establishing a SSH connection to 172.31.6.56.
> ⚠️ The GitHub Action couldn't connect to 172.31.6.56. Error: Timed out while waiting for handshake
>     at Timeout._onTimeout (/home/runner/work/_actions/garygrossgarten/github-action-ssh/release/node_modules/ssh2/lib/client.js:695:19)
>     at listOnTimeout (internal/timers.js:531:17)
>     at processTimers (internal/timers.js:475:7) {
>   level: 'client-timeout'
> }
>  1: 0x9da7c0 node::Abort() [/home/runner/runners/2.168.0/externals/node12/bin/node]
>  2: 0xa4e219  [/home/runner/runners/2.168.0/externals/node12/bin/node]
>  3: 0xba5d59  [/home/runner/runners/2.168.0/externals/node12/bin/node]
>  4: 0xba7b47 v8::internal::Builtin_HandleApiCall(int, unsigned long*, v8::internal::Isolate*) [/home/runner/runners/2.168.0/externals/node12/bin/node]
>  5: 0x13750d9  [/home/runner/runners/2.168.0/externals/node12/bin/node]

NOTE: I can connect using this ssh command:

`ssh -i ~/.ssh/private.key ubuntu@172.31.6.56`

So there must be wrong between using the privateKey on this action because it works with the private key file ?

**Comment by bblanchon** [comment]
Hi @devcarlos,

`172.31.6.56` is a [private address](https://en.wikipedia.org/wiki/Private_network).
As such, it can only be used in a private network but not on the Internet.
This explains why you can SSH, from your machine, but not from the GitHub Action.

Best regards,
Benoit
