### ISSUE TITLE
Update to node20

### ISSUE THREAD

**Issue by Marv51** [garygrossgarten/github-action-ssh#40]
I am getting a deprecation message about node 16:

> Node.js 16 actions are deprecated. Please update the following actions to use Node.js 20: garygrossgarten/github-action-ssh@release. For more information see: https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/.

I am not sure what exactly deprecated means in this context. Potentially in the future, this action will stop working on normal runners?

I see that this action hasn't been updated in a while, but it works great for me. Please consider updating the action for this.

**Comment by brennanwilkes** [comment]
Any update on this @garygrossgarten

**Comment by garygrossgarten** [comment]
The node version has been updated in the latest release 0.8.0. Thanks for your patience.
